#!/usr/bin/env python3
"""Cycle 2 adversarial + false-positive cases for guard_git.py, plus timing."""
import json, os, subprocess, sys, tempfile, time, statistics
GUARD = "/Users/mgarriga/claude-assistant/scripts/guard_git.py"
PY = sys.argv[1] if len(sys.argv) > 1 else "/usr/bin/python3"
root = os.path.realpath(tempfile.mkdtemp())
ws = os.path.join(root, "ws"); repos = os.path.join(root, "Repos")
os.makedirs(ws); os.makedirs(repos)
def mk(path, branch):
    os.makedirs(path, exist_ok=True)
    subprocess.run(["git","init","-q","-b",branch,path],check=True)
    subprocess.run(["git","-C",path,"-c","user.name=t","-c","user.email=t@t","commit","-q","--allow-empty","-m","i"],check=True)
mk(ws,"main"); mk(os.path.join(repos,"rmain"),"main"); mk(os.path.join(repos,"rfeat"),"feature/x")
tmp = os.path.join(root,"tmpdir"); os.makedirs(tmp)
R = lambda n: os.path.join(repos,n)
def run(cmd,cwd=None):
    env = dict(os.environ, CLAUDE_PROJECT_DIR=ws)
    return subprocess.run([PY,GUARD],input=json.dumps({"tool_input":{"command":cmd},"cwd":cwd or ws}),capture_output=True,text=True,env=env).returncode
cases=[]
def c(l,cmd,exp,cwd=None,info=False): cases.append((l,cmd,cwd,exp,info))
GP="git "+"push"
# adversarial
c("nested bash -c sh -c", f"bash -c \"sh -c '{GP}'\"", True)
c("triple nested", f"bash -c \"bash -c \\\"sh -c '{GP}'\\\"\"", True)
c("eval $(echo git push)", "eval $(echo git push)", True, info=True)
c("eval string", f"eval '{GP}'", True)
c("time -p git push", "time -p "+GP, True)
c("git -c -C push", "git -c core.x=y -C dir push", True)
c("git -C after cd /tmp commit main", f"cd {tmp} && git -C {R('rmain')} commit -m x", True)
c("git -C relative after cd", f"cd {tmp} && git -C ../Repos/rmain commit -m x", True)
c("checkout main && commit under Repos", f"cd {R('rfeat')} && git checkout main && git commit -m x", True)
c("switch -c feature && commit under Repos main", f"cd {R('rmain')} && git switch -c feature/EBS-1 && git commit -m x", False)
c("checkout -b feature && commit", "git checkout -b feature/EBS-2 && git commit -m x", False, R("rmain"))
c("heredoc then real push", "cat <<EOF\nhello git push\nEOF\n"+GP, True)
c("heredoc prose only", "cat <<'EOF'\nrun git push later\nEOF", False)
c("heredoc commit message", "git commit -F - <<EOF\nfix: git push docs\nEOF", False, R("rfeat"))
c("cat <<EOF | bash git push", "cat <<EOF | bash\n"+GP+"\nEOF", True, info=True)
c("bash <<EOF push", "bash <<EOF\n"+GP+"\nEOF", True, info=True)
c("echo | sh", f"echo '{GP}' | sh", True, info=True)
c("bash -lc push", f"bash -lc '{GP}'", True)
c("bash -c with flags -e", f"bash -e -c '{GP}'", True)
c("xargs git push", "echo x | xargs git push", True)
c("find -exec git push", "find . -exec git push \;", True)
c("git push after comment line", "# note\n"+GP, True)
c("git push in subshell cd", f"(cd {tmp} && {GP})", True)
c("git push --force-with-lease", GP+" --force-with-lease", True)
c("git merge --ff-only", "git merge --ff-only x", True)
c("git pull (not blocked, fetch+merge)", "git pull", False, info=True)
c("git reset --hard HEAD~1", "git reset --hard HEAD~1", True)
c("git stash && commit main", "git stash && git commit -m x", True, R("rmain"))
c("commit in repo via GIT_DIR env", f"GIT_DIR={R('rmain')}/.git git commit -m x", True, ws, info=True)
c("git alias via config command", "git config alias.p push", False, info=True)
c("npx sutecloud typo? real npx", "npx "+"suite"+"cloud account:setup", True)
c("tab separated", "git\tpush", True)
c("semicolon no space", "ls;git push", True)
c("backtick push", f"echo `{GP}`", True)
# false positives / legit
c("git status && diff --stat","git status && git diff --stat",False)
c("git log --oneline -5","git log --oneline -5",False)
c("add -A && commit msg merge, feature","git add -A && git commit -m \"fix: handle merge of lines\"",False,R("rfeat"))
c("commit msg with git push words, feature","git commit -m \"docs: explain git push is Matt's job\"",False,R("rfeat"))
c("commit msg push, main in workspace","git commit -m \"docs: git push rule\"",False,ws)
c("commit msg heredoc $(cat) feature","git commit -m \"$(cat <<'EOF'\nfix: push and merge notes\nEOF\n)\"",False,R("rfeat"))
c("commit in workspace main", "git add -A && git commit -m x", False, ws)
c("npm test","npm test",False)
c("node cli","node lib/docx/cli.js sdd x.json out.docx",False)
c("lint_voice","python3 scripts/lint_voice.py file.md",False)
c("lint_voice design","python3 scripts/lint_voice.py --design file.md",False)
c("grep git push","grep -rn \"git push\" docs/",False)
c("grep -rn merge","grep -rn 'merge' docs/ | head",False)
c("pandoc","pandoc -t markdown x.docx",False)
c("soffice","soffice --headless --convert-to pdf x.docx",False)
c("pdftoppm","pdftoppm -png -r 80 x.pdf out",False)
c("echo push","echo 'remember to git push' > notes.txt",False)
c("git diff main..feature","git diff main..HEAD",False)
c("git branch -a","git branch -a",False)
c("git branch --show-current","git branch --show-current",False)
c("git checkout -- file","git checkout -- file.md",False)
c("git checkout feature","git checkout feature/x",False,R("rfeat"))
c("git switch main (no commit)","git switch main",False,R("rfeat"))
c("git stash","git stash",False)
c("git fetch","git fetch origin",False)
c("git worktree / rev-parse","git rev-parse --abbrev-ref HEAD",False)
c("cd Repos main && git status","cd ../Repos/rmain && git status && git log -3",False)
c("cd Repos main && git diff","cd "+R('rmain')+" && git diff HEAD~0",False)
c("git commit --dry-run main? (judged as commit)","git commit --dry-run",True,R("rmain"),info=True)
c("sed push in file","sed -i '' 's/git push/git pull/' docs/x.md",False)
c("branch name with f: git branch -vv","git branch -vv",False)
c("git log --format with -f? git log -p","git log -p -n 3",False)
c("git clean -n","git clean -n",False)
c("git clean -fd (force blocked)","git clean -fd",True)
c("git checkout -b feat/x-f","git checkout -b feature/fix-f",False,R("rfeat"))
c("git branch feature/foo-d","git branch feature/foo-d",False,R("rfeat"))
c("for loop ls","for f in *.md; do python3 scripts/lint_voice.py \"$f\"; done",False)
c("subshell cd leak then commit feature","(cd "+R('rmain')+" && git status); git commit -m x",False,R("rfeat"))  # quirk
c("$( ) in dq normal","echo \"today is $(date +%F)\"",False)
c("$( ) in dq with git status","echo \"branch: $(git rev-parse --abbrev-ref HEAD)\"",False)
c("$( ) in dq w/ cd","echo \"$(cd docs && ls)\" && git commit -m x",False,R("rfeat"))
c("mkdir/cp/ls","mkdir -p clients/x/outputs && cp a b && ls -la",False)
c("curl|jq","curl -s https://example.com | jq .",False)
c("python3 heredoc","python3 - <<'PY'\nprint('git push')\nPY",False)
c("gh pr view","gh pr list",False)
c("git -C Repos log","git -C ../Repos/rmain log --oneline -3",False)
fails=[]; infos=[]
for l,cmd,cwd,exp,info in cases:
    rc=run(cmd,cwd); b=(rc==2)
    ok = b==exp and rc in (0,2)
    if info: infos.append((l,"BLOCK" if b else "ALLOW", "BLOCK" if exp else "ALLOW"))
    elif not ok: fails.append((l,cmd,exp,rc))
print(f"total={len(cases)} info={len(infos)} fail={len(fails)}")
for f in fails: print("FAIL",f)
for i in infos: print("INFO",i)
# timing
ts=[]
for _ in range(100):
    t=time.perf_counter(); run("git status && git diff --stat | head",R("rfeat")); ts.append((time.perf_counter()-t)*1000)
ts2=[]
for _ in range(100):
    t=time.perf_counter(); run("ls -la docs/",ws); ts2.append((time.perf_counter()-t)*1000)
print("median ms git cmd",statistics.median(ts),"max",max(ts)); print("median ms plain",statistics.median(ts2),"max",max(ts2))
